### ISSUE TITLE
makepkg --noconfirm

### ISSUE THREAD

**Issue by xantares** [hv15/tllocalmgr#2]
from a script, unless I replace the "makepkg -i" command by "makepkg -i --noconfirm", pacman asks for interactive confirmation and the package never gets installed:

```
:: Proceed with installation? [Y/n] 
Package (1)            New Version  Net Change

texlive-local-fourier  61937-1        1.14 MiB

Total Installed Size:  1.14 MiB

==> WARNING: Failed to install built package(s).
```

I cannot think of something else to use be able to use tllocalmgr from a script

**Comment by hv15** [comment]
Hmmmm, I hadn't considered that tllocalmgr would be called from a script. Would it makes sense for tllocalmgr to provide a command like `genpkgbuild` which would output the PKGBUILD file? You could call `makepkg` directly in your script then.

**Comment by xantares** [comment]
that would be too much extra steps, maybe just add an option to pass --noconfirm to makepkg ?

**Comment by hv15** [comment]
sorry for not replying sooner, I was busy with life. please see the latest commit, or https://aur.archlinux.org/packages/tllocalmgr-git.
