### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by agustiner** [hv15/tllocalmgr#5]
Hi, getting a simple install error.

```
$ git clone https://aur.archlinux.org/tllocalmgr.git
Cloning into 'tllocalmgr'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), done. 
$ cd tllocalmgr/
$ makepkg -sr
==> Making package: tllocalmgr 0.8-1 (Fri 23 Dec 2022 01:13:06 PM PST)
==> Checking runtime dependencies...
==> Installing missing dependencies...
[sudo] password for user1: 
error: target not found: perl-term-shellui
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> perl-libwww
  -> perl-term-shellui
  -> perl-term-readline-gnu
  -> perl-list-moreutils
  -> perl-lwp-protocol-https
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

I believe `perl-term-shellui` should be replaced with `perl-term-ui`? [Ref](https://archlinux.org/packages/?sort=&q=perl-term-ui&maintainer=&flagged=).

**Comment by hv15** [comment]
Hi @agustiner, `perl-term-shellui` is the correct dependency. `perl-term-ui` doesn't provide the Term::ShellUI module. Using makepkg is fine, but be aware that pacman cannot download/install AUR packages, you'll need to do this manually and install in the correct order, or use a [AUR helper](https://wiki.archlinux.org/title/AUR_helpers#Pacman_wrappers) to do this for you. I hope that helps! Also Seasons Greeting!

**Comment by agustiner** [comment]
Makes sense, thanks!
