### ISSUE TITLE
cannot find installed package

### ISSUE THREAD

**Issue by harishnkr** [hv15/tllocalmgr#8]
Hey, thanks for the package first of all ! I know it is difficult to maintain documentation all on your own so can you help me understand where the packages are installed ? 

I tried installing a font via tllocalmgr. Installation seems successful. But i don't know where the font is installed. fc-list does not show the font, even after running fc-cache. Any help would be appreciated.

**Comment by hv15** [comment]
Hi, thank you!

Regarding fonts, they are usually not part of the font cache as they are meant to only be used in TeX/LaTeX/DVI/PS projects. The font files should be somewhere under `/var/lib/texmf/`.

**Comment by harishnkr** [comment]
Thanks
