### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by esbon125** [hv15/tllocalmgr#9]
Hi, I installed from the AUR, everything seemed to go right with the installation, but I can't run the program correctly, as I get this error:
```
$ tllocalmgr
Retrieving new TeXLive database from CTAN...
could not fetch http://mirror.ctan.org/systems/texlive/tlnet/tlpkg/texlive.tlpdb.xz :
500 Can't connect to mirror.ctan.org:80 (No route to host) at /usr/bin/tllocalmgr line 107.
```

**Comment by hv15** [comment]
Hi @esbon125, have you checked that you can resolve http://mirror.ctan.org, it is possible that your DNS server is not resolving the domain correctly. If I remember correctly, the domain does a redirect to your geo-ip closest mirror server, it could be that the closest server is down as well.

**Comment by esbon125** [comment]
Today I turned on the computer and it worked perfectly. Thanks for answering
